# Generated by Django 5.2.16 on 2026-07-28 22:43

import django.db.models.deletion
import tom_common.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0030_alter_basetarget_slope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFHTProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfht_access_token', tom_common.encryption.EncryptedModelField(blank=True, editable=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KealahouProgramAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_token', models.CharField(help_text="Kealahou's unique identifier for the program (runid-shaped, e.g. '25BE25').", max_length=32, unique=True)),
                ('target_list', models.ForeignKey(help_text='The Target Grouping whose membership mirrors this program in the TOM.', on_delete=django.db.models.deletion.CASCADE, related_name='kealahou_program_associations', to='tom_targets.targetlist')),
            ],
        ),
        migrations.CreateModel(
            name='KealahouTargetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_token', models.CharField(help_text="Kealahou's unique identifier for the program (runid-shaped, e.g. '25BE25').", max_length=32)),
                ('kealahou_target_token', models.CharField(help_text="Kealahou's unique identifier for the target within its program, e.g. '25BE25-1758314224958'. Client-generated at upload.", max_length=64, unique=True)),
                ('version', models.IntegerField(blank=True, help_text="Kealahou's optimistic-lock version, as returned by the API after the last sync. Sent back as lock_version on updates to prevent overwriting concurrent edits.", null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this link was last created or refreshed by a sync operation.')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kealahou_links', to='tom_targets.basetarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'program_token'), name='unique_target_per_program')],
            },
        ),
    ]
